# print("sumeet")
# # #exception handling
# # x = "Sumeet"
# # y = int(x)
# # z = 1+ y
# # print(Z)
# try:
#     x = "Sumeet"
#     y = int(x)
#     z = 1+ y
#     print(Z)
# except ValueError:
#    print("Something went wrong")

